# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ca3f422162587dafb4170d135bfbd905fde06565fe9237c605f49f70ddcb7851dd664402139e8af7c2c25c070ab11b6d60ba0299e0c528698b740bda7a2a4ae

test:
  secret_key_base: b5658d5b5ca20dd54ec6a091ed83c5c5614e77cef1ed271cf782d5a8ca3a5ac6d80561d5a04eb96e6f03003981c839521a92ca0adb490bfb83ecf5eb6658fc8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
